### ISSUE TITLE
Missing # in reversed urls?

### ISSUE THREAD

**Issue by marcinn** [domasx2/angular-named-route#2]
Hi! I have a question / problem. I'm trying to use named routes with Angular 1.3.16, but `reverse()` generates URLs (`href`) without `#` sign, so they points to backend (server) instead of client (angular app). How to set prefix to `/#` or `#`?

**Comment by domasx2** [comment]
I haven't considered this case, I always use html5 mode only. Will fix

**Comment by domasx2** [comment]
Implemented by inspecting $location for html5 mode and getting the configured hash prefix from $locationProvider. Bumped version to 2.0.0, I think using angular's versioning number wasn't a great idea...

**Comment by marcinn** [comment]
Works like a charm. Thank you! :beers:
