### ISSUE TITLE
Support for URL query parameters

### ISSUE THREAD

**Issue by marcinn** [domasx2/angular-named-route#4]
It would be nice to set URL query parameters directly from directive.

Example:

```
<a named-route="'item-list'" route-query-args="{group: 5}">...</a>
```

which should generate something like `<a href="/items/?group=5">..</a>`.

**Comment by domasx2** [comment]
implemented with https://github.com/domasx2/angular-named-route/commit/466946da89845847650106039804944482196632

it's route-query-params though, not route-query-args :)
