### ISSUE TITLE
Add support for relative links using base

### ISSUE THREAD

**Issue by eddieantonio** [domasx2/angular-named-route#6]
The named routes created by `reverse()` do not take `<base>` into account when (i.e., when `html5Mode.requireBase` is true). The relative URLs should include the base when using HTML 5 links

See [Relative Links](https://docs.angularjs.org/guide/$location#relative-links).

**Comment by domasx2** [comment]
Hi, any chance for a PR?

**Comment by eddieantonio** [comment]
I may have a bit of time after this sprint. Currently I have a terrible
workaround in my app, but I'll be happy to have something more elegant for
the next sprint!
